matrix:
  include:
    - language: python
      sudo: required
      dist: xenial
      python:
        - "3.7"

      install:
        - pip install -r python/requirements.txt

      script:
        - mypy python/
        - pytest --cov-report=xml --cov=python/guessthenumber/

      after_success:
        - coveralls

    - language: rust

      script:
        - cd ./rust/guessthenumber/
        - cargo build --verbose --all
        - cargo test --verbose --all
